/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/studio/glyphdance-theme.ts
 * Command: astryx theme build src/studio/glyphdance-theme.ts
 * CLI: @astryxdesign/cli@0.6.2-canary.605fa9a
 * Core: @astryxdesign/core@0.6.2-canary.605fa9a
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
