/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/studio/glyphdance-theme.ts
 * Command: astryx theme build src/studio/glyphdance-theme.ts
 * CLI: @astryxdesign/cli@0.6.2-canary.605fa9a
 * Core: @astryxdesign/core@0.6.2-canary.605fa9a
 */

/// <reference path="./glyphdance.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const glyphdanceTheme: DefinedTheme;
